#!/usr/bin/env python3
"""
Generate the LaTeX tables and the machine-readable number manifest of the ANADEF-Hokkaido
manuscript directly from the pipeline outputs, so that no reported value is transcribed by hand.

    python3 make_tables.py --main data/output_FINAL \
        --globalmc data/output_FINAL_globalMc --train2004 data/output_FINAL_train2004 \
        --m55 data/output_FINAL_M55 --out manuscript_tables

Writes tab2.tex (ETAS parameters), tab3.tex (retrospective performance), tab4.tex (out-of-sample
and sensitivity), tab_paired.tex (paired bootstrap of the skill differences) and
manuscript_numbers.json (every value quoted in the text, keyed by name).
"""
import argparse
import json
import os

import numpy as np
import pandas as pd

MODEL_LABEL = {'uniform random': 'uniform random',
               'mu only': '$\\mu$ only (Level 1)',
               'smoothed seismicity': 'smoothed seismicity (1b)',
               'b only': '$b$ only (Level 2)',
               'joint (b+mu)': 'joint $b \\wedge \\mu$ (Level 3)'}
PAIR_LABEL = {'joint - mu': 'joint $-$ $\\mu$', 'joint - b': 'joint $-$ $b$', 'mu - b': '$\\mu$ $-$ $b$',
              'mu - smooth': '$\\mu$ $-$ smoothed', 'joint - smooth': 'joint $-$ smoothed'}


def load(run_dir):
    with open(os.path.join(run_dir, 'run_summary.json')) as f:
        s = json.load(f)
    key = [k for k in s['windows'] if 'evaluation' in s['windows'][k]][0]
    return s, s['windows'][key], key


def f(x, n=3):
    return '--' if x is None or (isinstance(x, float) and not np.isfinite(x)) else f'{x:.{n}f}'


# ---------------------------------------------------------------- Table 2: ETAS parameters
def table2(summary, out):
    w = sorted(summary['windows'])
    P = []
    for lab in w:
        with open(os.path.join(out['dir'], f'etas_params_{lab}.json')) as fh:
            P.append(json.load(fh))
    se = [p['standard_errors'] for p in P]
    rows = [('events $M \\ge 3.0$', [f"{p['n_events']}" for p in P]),
            ('$K$ (yr$^{-1}$)', [f"${f(p['K_yr'])} \\pm {f(e['K_yr'])}$" for p, e in zip(P, se)]),
            ('$\\alpha$', [f"${f(p['alpha'], 2)} \\pm {f(e['alpha'], 2)}$" for p, e in zip(P, se)]),
            ('$c$ (min)', [f"${f(p['c_days'] * 1440, 1)}$ (at bound)" for p in P]),
            ('$p$', [f"${f(p['p'], 2)} \\pm {f(e['p'], 2)}$" for p, e in zip(P, se)]),
            ('$D$ ($10^{-4}$~deg$^2$)', [f"${f(p['D_deg2'] * 1e4, 1)} \\pm {f(e['D_deg2'] * 1e4, 1)}$" for p, e in zip(P, se)]),
            ('$q$', [f"${f(p['q'], 2)} \\pm {f(e['q'], 2)}$" for p, e in zip(P, se)]),
            ('$\\gamma$', [f"${f(p['gamma'], 2)} \\pm {f(e['gamma'], 2)}$" for p, e in zip(P, se)]),
            ('$\\mu_0$ (events deg$^{-2}$ yr$^{-1}$)',
             [f"${f(p['mu0_per_deg2_yr'], 2)} \\pm {f(e['mu0_per_deg2_yr'], 2)}$" for p, e in zip(P, se)]),
            ('offspring per $M_c$ parent in window', [f(p['offspring_per_Mc_parent_in_window'], 2) for p in P]),
            ('background fraction $\\bar\\varphi$', [f(p['background_fraction_empirical'], 2) for p in P]),
            ('mean $\\varphi$ of $M \\ge 5$ events', [f(p['phi_mean_M5plus'], 2) for p in P])]
    L = ['% generated by make_tables.py - do not edit', '\\begin{tabular}{@{}lcc@{}}', '\\toprule',
         'parameter & ' + ' & '.join(x.replace('-', '--') for x in w) + ' \\\\', '\\midrule']
    L += [f'{n} & ' + ' & '.join(v) + ' \\\\' for n, v in rows]
    L += ['\\bottomrule', '\\end{tabular}']
    return '\n'.join(L) + '\n'


# ---------------------------------------------------------------- Table 3: retrospective performance
def table3(t3, out):
    L = ['% generated by make_tables.py - do not edit',
         '\\begin{tabular}{@{}llcccccc@{}}', '\\toprule',
         'target & model & $S$ (95\\,\\% CI) & max PD & $\\tau$ & $\\nu$ & $b_{\\mathrm{thr}}$ & $\\mu_{\\mathrm{thr}}$ \\\\',
         '\\midrule']
    for i, (tgt, grp) in enumerate(t3.groupby('target', sort=False)):
        if i:
            L.append('\\midrule')
        N = tgt.split('N=')[1].rstrip(')')
        mlab = tgt.split(' ')[0].replace('M>=', 'M \\ge ')
        head = ['$' + mlab + '$', '($N = ' + N + '$)'] + [''] * (len(grp) - 2)
        for h, (_, r) in zip(head, grp.iterrows()):
            if r['model'] == 'uniform random':
                L.append(f"{h} & uniform random & 0 & 0 & -- & -- & -- & -- \\\\")
                continue
            ci = f"{f(r['S'])} ({f(r['S_ci_low'], 2)}--{f(r['S_ci_high'], 2)})"
            L.append(f"{h} & {MODEL_LABEL[r['model']]} & {ci} & {f(r['max_PD'])} & {f(r['tau_at_max'])} & "
                     f"{f(r['nu_at_max'])} & {f(r['b_thr'])} & {f(r['mu_thr'])} \\\\")
    L += ['\\bottomrule', '\\end{tabular}']
    return '\n'.join(L) + '\n'


# ---------------------------------------------------------------- paired bootstrap table
# Comparisons reported in the manuscript.  The full set, including the pairs whose difference the
# 71 targets do not resolve, is written to paired_bootstrap_<window>.csv with the other run outputs.
REPORTED_PAIRS = ['mu - b', 'joint - b', 'mu - smooth']


def table_paired(pb):
    pb = pb[pb['pair'].isin(REPORTED_PAIRS)].copy()
    L = ['% generated by make_tables.py - do not edit', '\\begin{tabular}{@{}llccc@{}}', '\\toprule',
         'target & models compared & $\\Delta S$ & 95\\,\\% CI & $p$ \\\\', '\\midrule']
    for i, (tgt, grp) in enumerate(pb.groupby('target', sort=False)):
        if i:
            L.append('\\midrule')
        N = tgt.split('N=')[1].rstrip(')')
        mlab = tgt.split(' ')[0].replace('M>=', '')
        head = ['$M \\ge ' + mlab + '$ ($N = ' + N + '$)'] + [''] * (len(grp) - 1)
        for h, (_, r) in zip(head, grp.iterrows()):
            p = '$< 0.001$' if r['p_two_sided'] < 0.001 else f"${f(r['p_two_sided'], 3)}$"
            L.append(f"{h} & {PAIR_LABEL[r['pair']]} & ${f(r['delta'])}$ & "
                     f"$[{f(r['ci_low'])},\\ {f(r['ci_high'])}]$ & {p} \\\\")
    L += ['\\bottomrule', '\\end{tabular}']
    return '\n'.join(L) + '\n'


# ---------------------------------------------------------------- Table 4: split-half + sensitivity
def table4(runs, target='5.0'):
    main = runs['main'][1]['evaluation']
    L = ['% generated by make_tables.py - do not edit', '\\begin{tabular}{@{}lccccc@{}}', '\\toprule',
         '\\multicolumn{6}{@{}l}{\\textit{Split-half validation}} \\\\',
         'direction & $\\mu$ PD in & $\\mu$ PD out & joint PD in & joint PD out & $q_b$ \\\\', '\\midrule']
    for r in main['split_half'][target]:
        d = '2012--2017 $\\to$ 2018--2023' if r['direction'].startswith('first') else '2018--2023 $\\to$ 2012--2017'
        L.append(f"{d} & {f(r['mu_in_PD'])} & {f(r['mu_out_PD'])} & {f(r['joint_in_PD'])} & "
                 f"{f(r['joint_out_PD'])} & {f(r['joint_q_b'], 2)} \\\\")
    L += ['\\midrule', '\\multicolumn{6}{@{}l}{\\textit{Sensitivity runs}} \\\\',
          'run & $S_\\mu$ / $S_{\\mathrm{smooth}}$ & $S_b$ & $S_{\\mathrm{joint}}$ & PD joint / $\\mu$ & $p$ (PD) \\\\',
          '\\midrule']
    names = {'main': 'main', 'globalmc': 'single $M_c = 3.0$', 'train2004': 'training 2004--2011',
             'm55': 'calibrated on $M \\ge 5.5$'}
    for key in ['main', 'globalmc', 'train2004', 'm55']:
        if key not in runs:
            continue
        ev = runs[key][1]['evaluation']
        t = pd.DataFrame(ev['table3'])
        t = t[t['target'].str.startswith(f'M>={target}')].set_index('model')
        perm = ev['permutation'][target]['PD']
        S = lambda m: f(t.loc[m, 'S'])
        L.append(f"{names[key]} & {S('mu only')} / {S('smoothed seismicity')} & {S('b only')} & "
                 f"{S('joint (b+mu)')} & {f(t.loc['joint (b+mu)', 'max_PD'])} / {f(t.loc['mu only', 'max_PD'])} & "
                 f"{f(perm['p_cell_shuffle'])} / {f(perm['p_toroidal_shift'])} \\\\")
    L += ['\\bottomrule', '\\end{tabular}']
    return '\n'.join(L) + '\n'


# ---------------------------------------------------------------- the number manifest
def manifest(runs, t3, pb):
    s, wmain, key = runs['main']
    ev = wmain['evaluation']
    t = t3[t3['target'].str.startswith('M>=5.0')].set_index('model')
    M = {'catalogue': {'n_events': s['n_events'], 'grid_cells': s['grid_cells'], 'bbox': s['bbox']},
         'thresholds': ev['thresholds'],
         'skill_M5.0': {m: {'S': t.loc[m, 'S'], 'ci': [t.loc[m, 'S_ci_low'], t.loc[m, 'S_ci_high']],
                            'max_PD': t.loc[m, 'max_PD'], 'tau': t.loc[m, 'tau_at_max'],
                            'nu': t.loc[m, 'nu_at_max'], 'ZPD': t.loc[m, 'ZPD_at_max'],
                            'PG': t.loc[m, 'PG_at_max']} for m in t.index if m != 'uniform random'},
         'paired_bootstrap': pb.to_dict(orient='records'),
         'permutation': ev['permutation'],
         'split_half': ev['split_half'],
         'forward': s.get('forward', {}),
         'sensitivity_p_PD': {k: runs[k][1]['evaluation']['permutation']['5.0']['PD'] for k in runs}}
    for w in s['windows']:
        M.setdefault('etas', {})[w] = {k: v for k, v in s['windows'][w].items() if not isinstance(v, dict)}
    return M


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--main', required=True)
    ap.add_argument('--globalmc'), ap.add_argument('--train2004'), ap.add_argument('--m55')
    ap.add_argument('--out', default='manuscript_tables')
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)

    runs = {}
    for k in ['main', 'globalmc', 'train2004', 'm55']:
        d = getattr(a, k)
        if d:
            s, w, key = load(d)
            runs[k] = (s, w, key, d)
    s, wmain, key, maindir = runs['main']
    tlab = wmain['evaluation']['test_window']
    t3 = pd.read_csv(os.path.join(maindir, f'table3_{key}_{tlab}.csv'))
    pbp = os.path.join(maindir, f'paired_bootstrap_{key}_{tlab}.csv')
    pb = pd.read_csv(pbp) if os.path.exists(pbp) else pd.DataFrame()

    written = []
    for name, text in [('tab2.tex', table2(s, {'dir': maindir})),
                       ('tab3.tex', table3(t3, maindir)),
                       ('tab4.tex', table4({k: v[:2] for k, v in runs.items()}))]:
        with open(os.path.join(a.out, name), 'w') as fh:
            fh.write(text)
        written.append(name)
    if len(pb):
        with open(os.path.join(a.out, 'tab_paired.tex'), 'w') as fh:
            fh.write(table_paired(pb))
        written.append('tab_paired.tex')
    with open(os.path.join(a.out, 'manuscript_numbers.json'), 'w') as fh:
        json.dump(manifest({k: v[:3] for k, v in runs.items()}, t3, pb), fh, indent=2, default=float)
    written.append('manuscript_numbers.json')
    print('wrote ' + ', '.join(os.path.join(a.out, w) for w in written))


if __name__ == '__main__':
    main()
